name: weather_project_1
description: A cosmic-themed animated weather demo built with Flutter.
publish_to: 'none' # Per evitare la pubblicazione accidentale su pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ðŸŒŒ Dipendenze core
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  lottie: ^3.1.0
  encrypt: ^5.0.3
  path_provider: ^2.1.3
  convert: ^3.1.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/.env.demo
    - assets/animations/sunny.json
    - assets/animations/cloudy.json
    - assets/animations/night.json
    - assets/animations/rain.json
    - assets/animations/snow.json
    - assets/animations/fog.json

